recipe: default.v1

assistant_id: 20241022-131940-global-void

language: id

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.9
    ambiguity_threshold: 0.5

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.7
    core_fallback_action_name: "action_call_gpt"
    enable_fallback_prediction: True
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
