version: '3.8'

services:
  rasa:
    image: rasa/rasa:latest
    volumes:
      - ./app:/app
    ports:
      - 5005:5005
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    networks:
      - rasa_network

  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
    networks:
      - rasa_network

networks:
  rasa_network:
